#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=deploy/scripts/lib-env.sh
source "$SCRIPT_DIR/lib-env.sh"

REPO_ROOT="$(project_repo_root)"
PROJECT_ENV_FILE="${1:-$(project_env_file)}"
ROOT_ENV_FILE="$REPO_ROOT/.env.prod"
API_ENV_FILE="$REPO_ROOT/api/.env.prod"

load_env_file "$PROJECT_ENV_FILE"

require_env_vars \
  APP_FE_ORIGIN \
  APP_NAME \
  PROJECT_NAME \
  BASE_API_PREFIX \
  API_VERSION \
  PORT \
  JWT_TOKEN_SECRET \
  INTERNAL_AUTH_TOKEN \
  AUTH_LOG_TOKEN \
  PG_USER \
  PG_PASSWORD \
  PG_DBNAME

export APP_ENV="${APP_ENV:-production}"
export LOKI_SCHEME="${LOKI_SCHEME:-http}"
export LOKI_HOST="${LOKI_HOST:-loki}"
export LOKI_PORT="${LOKI_PORT:-3100}"
export LOKI_HOST_PORT="${LOKI_HOST_PORT:-3100}"
export LOKI_BASE_URL="$(derive_loki_base_url)"

if [[ -z "${M_MAIN_CLIENT_BASE_URL:-}" || "$M_MAIN_CLIENT_BASE_URL" == '${APP_FE_ORIGIN}' || "$M_MAIN_CLIENT_BASE_URL" == '$APP_FE_ORIGIN' ]]; then
  export M_MAIN_CLIENT_BASE_URL="$APP_FE_ORIGIN"
fi

if [[ -z "${PHOTO_STORAGE_PATH:-}" || "$PHOTO_STORAGE_PATH" == '${STORAGE_ROOT}/photo' || "$PHOTO_STORAGE_PATH" == '$STORAGE_ROOT/photo' ]]; then
  export PHOTO_STORAGE_PATH="${STORAGE_ROOT:-/app/storage}/photo"
fi

mkdir -p "$(dirname "$ROOT_ENV_FILE")" "$(dirname "$API_ENV_FILE")"

cat > "$ROOT_ENV_FILE" <<EOF
APP_FE_ORIGIN=$APP_FE_ORIGIN
EOF

cat > "$API_ENV_FILE" <<EOF
APP_ENV=$APP_ENV
APP_NAME=$APP_NAME
LOG_LEVEL=${LOG_LEVEL:-info}
GOFLAGS=${GOFLAGS:--mod=mod}
GOCACHE=${GOCACHE:-/app/.gocache}
STORAGE_ROOT=${STORAGE_ROOT:-/app/storage}
GATEWAY_MODE=${GATEWAY_MODE:-false}
OBSERVABLE=${OBSERVABLE:-false}
OBSERVABILITY_STACK_MANAGED_EXTERNALLY=${OBSERVABILITY_STACK_MANAGED_EXTERNALLY:-false}
PROJECT_NAME=$PROJECT_NAME
BASE_API_PREFIX=$BASE_API_PREFIX
API_VERSION=$API_VERSION
HOST=${HOST:-0.0.0.0}
PORT=$PORT
BODY_LIMIT_MB=${BODY_LIMIT_MB:-50}
JWT_TOKEN_SECRET=$JWT_TOKEN_SECRET
INTERNAL_AUTH_TOKEN=$INTERNAL_AUTH_TOKEN
AUTH_LOG_TOKEN=$AUTH_LOG_TOKEN
RETRY_MAX_ATTEMPTS=${RETRY_MAX_ATTEMPTS:-3}
RETRY_DELAY=${RETRY_DELAY:-100ms}
DB_PROVIDER=${DB_PROVIDER:-postgres}
DB_AUTOMIGRATE=${DB_AUTOMIGRATE:-true}
PG_HOST=${PG_HOST:-postgres}
PG_PORT=${PG_PORT:-5432}
PG_USER=$PG_USER
PG_PASSWORD=$PG_PASSWORD
PG_DBNAME=$PG_DBNAME
PG_SSL=${PG_SSL:-disable}
PGDATA_DIR=${PGDATA_DIR:-./.data/prod/postgres}
MONGO_URI=${MONGO_URI:-}
MONGO_DATABASE=${MONGO_DATABASE:-}
MYSQL_HOST=${MYSQL_HOST:-127.0.0.1}
MYSQL_PORT=${MYSQL_PORT:-3306}
MYSQL_USER=${MYSQL_USER:-}
MYSQL_PASSWORD=${MYSQL_PASSWORD:-}
MYSQL_DBNAME=${MYSQL_DBNAME:-}
CACHE_TTL_SHORT=${CACHE_TTL_SHORT:-2m}
CACHE_TTL_MEDIUM=${CACHE_TTL_MEDIUM:-5m}
CACHE_TTL_LONG=${CACHE_TTL_LONG:-20m}
CACHE_TTL_STATIC=${CACHE_TTL_STATIC:-6h}
REDIS_HOST=${REDIS_HOST:-redis}
REDIS_PORT=${REDIS_PORT:-6379}
REDIS_USERNAME=${REDIS_USERNAME:-}
REDIS_PASSWORD=${REDIS_PASSWORD:-}
REDIS_CACHE_DB=${REDIS_CACHE_DB:-0}
REDIS_PUBSUB_DB=${REDIS_PUBSUB_DB:-1}
REDIS_STATUS_DB=${REDIS_STATUS_DB:-2}
REDIS_IS_CLUSTER=${REDIS_IS_CLUSTER:-false}
REDIS_USE_TLS=${REDIS_USE_TLS:-false}
REDISDATA_DIR=${REDISDATA_DIR:-./.data/prod/redis}
CB_INTERVAL=${CB_INTERVAL:-30s}
CB_TIMEOUT=${CB_TIMEOUT:-10s}
CB_CONSECUTIVE_FAILURES=${CB_CONSECUTIVE_FAILURES:-5}
OBSERVABILITY_SERVICE_NAME=${OBSERVABILITY_SERVICE_NAME:-$APP_NAME}
OBSERVABILITY_LOGS_ENABLED=${OBSERVABILITY_LOGS_ENABLED:-true}
OBSERVABILITY_LOG_LEVEL=${OBSERVABILITY_LOG_LEVEL:-info}
LOKI_SCHEME=$LOKI_SCHEME
LOKI_HOST=$LOKI_HOST
LOKI_PORT=$LOKI_PORT
LOKI_HOST_PORT=$LOKI_HOST_PORT
LOKI_BASE_URL=$LOKI_BASE_URL
LOKI_TENANT_ID=${LOKI_TENANT_ID:-}
LOKI_BEARER_TOKEN=${LOKI_BEARER_TOKEN:-}
LOKI_TIMEOUT=${LOKI_TIMEOUT:-5s}
LOKI_STREAM_SELECTOR=${LOKI_STREAM_SELECTOR:-{app="noah_api"}}
LOKI_MAX_QUERY_LIMIT=${LOKI_MAX_QUERY_LIMIT:-200}
CRON_CLEAR_REFRESH_TOKEN_ENABLED=${CRON_CLEAR_REFRESH_TOKEN_ENABLED:-true}
CRON_CLEAR_REFRESH_TOKEN_SCHEDULE=${CRON_CLEAR_REFRESH_TOKEN_SCHEDULE:-@every 1h}
CRON_CLEAR_DELETED_PHOTO_ENABLED=${CRON_CLEAR_DELETED_PHOTO_ENABLED:-true}
CRON_CLEAR_DELETED_PHOTO_SCHEDULE=${CRON_CLEAR_DELETED_PHOTO_SCHEDULE:-0 0 * * *}
CRON_EXPIRE_ORDER_CODE_ENABLED=${CRON_EXPIRE_ORDER_CODE_ENABLED:-true}
CRON_EXPIRE_ORDER_CODE_SCHEDULE=${CRON_EXPIRE_ORDER_CODE_SCHEDULE:-@every 17m}
CRON_CLEAR_EXPIRED_ORDER_CODE_ENABLED=${CRON_CLEAR_EXPIRED_ORDER_CODE_ENABLED:-true}
CRON_CLEAR_EXPIRED_ORDER_CODE_SCHEDULE=${CRON_CLEAR_EXPIRED_ORDER_CODE_SCHEDULE:-5 0 * * *}
CRON_DASHBOARD_CASE_DAILY_STATS_ENABLED=${CRON_DASHBOARD_CASE_DAILY_STATS_ENABLED:-true}
CRON_DASHBOARD_CASE_DAILY_STATS_SCHEDULE=${CRON_DASHBOARD_CASE_DAILY_STATS_SCHEDULE:-10 0 * * *}
CRON_DASHBOARD_CASE_DAILY_REMAKE_STATS_ENABLED=${CRON_DASHBOARD_CASE_DAILY_REMAKE_STATS_ENABLED:-true}
CRON_DASHBOARD_CASE_DAILY_REMAKE_STATS_SCHEDULE=${CRON_DASHBOARD_CASE_DAILY_REMAKE_STATS_SCHEDULE:-11 0 * * *}
CRON_DASHBOARD_CASE_DAILY_COMPLETED_STATS_ENABLED=${CRON_DASHBOARD_CASE_DAILY_COMPLETED_STATS_ENABLED:-true}
CRON_DASHBOARD_CASE_DAILY_COMPLETED_STATS_SCHEDULE=${CRON_DASHBOARD_CASE_DAILY_COMPLETED_STATS_SCHEDULE:-12 0 * * *}
CRON_DASHBOARD_CASE_DAILY_ACTIVE_STATS_ENABLED=${CRON_DASHBOARD_CASE_DAILY_ACTIVE_STATS_ENABLED:-true}
CRON_DASHBOARD_CASE_DAILY_ACTIVE_STATS_SCHEDULE=${CRON_DASHBOARD_CASE_DAILY_ACTIVE_STATS_SCHEDULE:-13 0 * * *}
M_AUTH_HOST=${M_AUTH_HOST:-127.0.0.1}
M_AUTH_PORT=${M_AUTH_PORT:-8083}
M_RBAC_HOST=${M_RBAC_HOST:-127.0.0.1}
M_RBAC_PORT=${M_RBAC_PORT:-8082}
PHOTO_STORAGE_PATH=${PHOTO_STORAGE_PATH:-${STORAGE_ROOT:-/app/storage}/photo}
M_MAIN_HOST=${M_MAIN_HOST:-127.0.0.1}
M_MAIN_PORT=${M_MAIN_PORT:-8078}
M_MAIN_DELIVERY_QR_SESSION_TTL_MINUTES=${M_MAIN_DELIVERY_QR_SESSION_TTL_MINUTES:-5}
M_MAIN_DELIVERY_QR_PROOF_IMAGE_MAX_SIZE_MB=${M_MAIN_DELIVERY_QR_PROOF_IMAGE_MAX_SIZE_MB:-5}
M_MAIN_CLIENT_BASE_URL=$M_MAIN_CLIENT_BASE_URL
M_METADATA_HOST=${M_METADATA_HOST:-127.0.0.1}
M_METADATA_PORT=${M_METADATA_PORT:-8079}
M_USER_HOST=${M_USER_HOST:-127.0.0.1}
M_USER_PORT=${M_USER_PORT:-8081}
M_ATTRIBUTE_HOST=${M_ATTRIBUTE_HOST:-127.0.0.1}
M_ATTRIBUTE_PORT=${M_ATTRIBUTE_PORT:-8090}
M_AUDITLOG_HOST=${M_AUDITLOG_HOST:-127.0.0.1}
M_AUDITLOG_PORT=${M_AUDITLOG_PORT:-8085}
M_PROFILE_HOST=${M_PROFILE_HOST:-127.0.0.1}
M_PROFILE_PORT=${M_PROFILE_PORT:-8084}
M_TOKEN_HOST=${M_TOKEN_HOST:-127.0.0.1}
M_TOKEN_PORT=${M_TOKEN_PORT:-8088}
M_FOLDER_HOST=${M_FOLDER_HOST:-127.0.0.1}
M_FOLDER_PORT=${M_FOLDER_PORT:-8091}
M_PHOTO_HOST=${M_PHOTO_HOST:-127.0.0.1}
M_PHOTO_PORT=${M_PHOTO_PORT:-8092}
M_REALTIME_HOST=${M_REALTIME_HOST:-127.0.0.1}
M_REALTIME_PORT=${M_REALTIME_PORT:-8096}
M_NOTIFICATION_HOST=${M_NOTIFICATION_HOST:-127.0.0.1}
M_NOTIFICATION_PORT=${M_NOTIFICATION_PORT:-8097}
M_OBSERVABILITY_HOST=${M_OBSERVABILITY_HOST:-127.0.0.1}
M_OBSERVABILITY_PORT=${M_OBSERVABILITY_PORT:-8097}
M_SEARCH_HOST=${M_SEARCH_HOST:-127.0.0.1}
M_SEARCH_PORT=${M_SEARCH_PORT:-1}
FRONTEND_HOST_PORT=${FRONTEND_HOST_PORT:-8080}
PUBLIC_DOMAIN=${PUBLIC_DOMAIN:-}
EOF

echo "Rendered $ROOT_ENV_FILE"
echo "Rendered $API_ENV_FILE"
