import { mapper } from "@root/core/mapper/auto-mapper";
import type { OrderItemProcessInProgressModel } from "../model/order-item-process-inprogress.model";

mapper.register<OrderItemProcessInProgressModel>({
  name: "OrderItemProcessInProgress",
  dtoToModelNaming: "snake_to_camel",
  modelToDtoNaming: "camel_to_snake",
  defaultModel: () => ({
    id: 0,
    processId: null,
    processName: null,
    prevProcessId: null,
    nextProcessId: null,
    orderItemCode: null,
    checkInNote: null,
    checkOutNote: null,
    orderItemId: null,
    orderId: null,
    productId: null,
    productCode: null,
    productName: null,
    sectionId: null,
    sectionName: null,
    assignedId: null,
    assignedName: null,
    startedAt: null,
    completedAt: null,
    updatedAt: "",
    availableTargets: null,
    mode: null,
    requiresDentistReview: null,
    dentistReviewRequestNote: null,
    dentistReviewId: null,
    dentistReviewStatus: null,
    dentistReviewResponseNote: null,
    dentistReview: null,
  }),
});
