server:
  host: "${M_NOTIFICATION_HOST}"
  port: ${M_NOTIFICATION_PORT}
  route: "/api/notification"

external: true

database:
  provider: "${DB_PROVIDER}"
  automigrate: ${DB_AUTOMIGRATE}
  postgres:
    host: "${PG_HOST}"
    port: ${PG_PORT}
    user: "${PG_USER}"
    password: "${PG_PASSWORD}"
    name: "${PG_DBNAME}"
    sslmode: "${PG_SSL}"

push:
  enabled: ${M_NOTIFICATION_PUSH_ENABLED}
  subject: "${M_NOTIFICATION_PUSH_SUBJECT}"
  public_key: "${M_NOTIFICATION_PUSH_PUBLIC_KEY}"
  private_key: "${M_NOTIFICATION_PUSH_PRIVATE_KEY}"
  ttl: "${M_NOTIFICATION_PUSH_TTL}"
  urgency: "${M_NOTIFICATION_PUSH_URGENCY}"
  allowed_types: []
